//updatePullRequests = "always"

pullRequests.grouping = [
  {
    name = "kevin_sbt_plugins",
    title = "Update Kevin's sbt plugins",
    filter = [
      {group = "io.kevinlee", artifact = "sbt-*"}
    ]
  },
  {
    name = "kevin_libs",
    title = "Update Kevin's libraries",
    filter = [
      {group = "io.kevinlee"}
    ]
  },
  {
    name = "typelevel_libs",
    title = "Update Typelevel libraries and libraries integrated with Typelevel libraries",
    filter = [
      {group = "org.typelevel"},
      {group = "io.circe"},
      {group = "co.fs2"}
    ]
  }
]
